paste0("{
  \"fields\":[
    \"customer_profile_id\"
    ,\"created_time\"
  ],
  \"filters\":[
    \"customer_profile_id.eq(",profile_list,")\"
    ,\"reporting_period.in(",start,"...",end,")\"
  ],
  \"metrics\":[
    \"net_follower_growth\"
    ,\"followers_gained\"
    ,\"impressions\"
    ,\"impressions_paid\"
    ,\"impressions_unique\"
    ,\"impressions_paid_unique\"
    ,\"reactions\"
    ,\"comments_count\"
    ,\"shares_count\"
    ,\"post_link_clicks\"
    ,\"likes\"
    ,\"post_engagements\"
    ,\"cta_clicks_login\"
    ,\"video_views\"
    ,\"video_views_unique\"
    ,\"video_views_10s_unique\"
    ,\"post_content_clicks_other\"
    ,\"engagements_other\"
    ,\"lifetime_snapshot.followers_count\"
    ,\"reactions\"
    ,\"saves\"
    ,\"story_replies\"
    ,\"email_contacts\"
    ,\"get_directions_clicks\"
    ,\"phone_call_clicks\"
    ,\"text_message_clicks\"
    ,\"website_clicks\"
  ],
  \"timezone\":\"America/Chicago\"
  ,\"page\":",page,"
}")
